version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: agent-workflow-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - agent-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: agent-workflow-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/agent-workflow?authSource=admin
      JWT_SECRET: your-jwt-secret-change-in-production
      PORT: 5000
      CLIENT_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - agent-network
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: agent-workflow-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000
      VITE_SOCKET_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - agent-network
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  agent-network:
    driver: bridge